<a href="https://colab.research.google.com/github/MasterAlvin/Spartacodingclub_Alvin/blob/master/_9_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98(PyTorch)_%EA%B8%B0%EC%B4%88_%EB%A6%AC%EB%B7%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 파이토치(PyTorch)

<img src="https://img1.daumcdn.net/thumb/R800x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbuUgoV%2FbtqwWZvcHHX%2Fd6XzIFBEfiuFb0UvyV4A50%2Fimg.jpg" width="300">

- 코드 출처: https://pytorch.org/tutorials/

## 파이토치의 구성요소

- `torch`: 텐서를 생성하는 라이브러리

- `torch.autograd`: 자동미분 기능을 제공하는 라이브러리

- `torch.nn`: 신경망을 생성하는 라이브러리

- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리

- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공

- `torch.legacy`(./nn/.optim): Torch로부터 포팅해온 코드

- `torch.onnx`: ONNX(Open Neural Network Exchange)

  - 서로 다른 프레임워크 간의 모델을 공유할 때 사용

## 텐서(Tensors)
- 넘파이(NumPy)의 ndarray와 유사

- GPU를 사용한 연산 가속도 가능

In [1]:
import torch 

In [3]:
torch.__version__

'1.9.0+cu102'

### 초기화 되지 않은 행렬 

In [4]:
x = torch.empty(4, 2)
print(x)

tensor([[2.4113e-04, 3.0721e-41],
        [3.3631e-44, 0.0000e+00],
        [       nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30]])


### 무작위로 초기화된 행렬

In [5]:
x = torch.rand(4,2)
print(x)

tensor([[0.8446, 0.1028],
        [0.0228, 0.8435],
        [0.3662, 0.5042],
        [0.5484, 0.0537]])


### dtype이 long, 0으로 채워진 텐서

In [6]:
x = torch.zeros(4, 2, dtype = torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [7]:
x = torch.tensor([3, 2.3])

print(x)

tensor([3.0000, 2.3000])


In [8]:
x = x.new_ones(2, 4, dtype = torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 2.6701,  0.0134,  0.5553, -2.0652],
        [-0.1597,  0.3146,  1.5987, -0.0846]])


### 텐서의 크기

In [10]:
print(x.size())

torch.Size([2, 4])


## 텐서의 연산(operations)

### 덧셈 1

In [11]:
print(x)

tensor([[ 2.6701,  0.0134,  0.5553, -2.0652],
        [-0.1597,  0.3146,  1.5987, -0.0846]])


In [13]:
y = torch.rand(2, 4)
print(y)
print(x + y)

tensor([[0.0093, 0.3187, 0.7728, 0.8845],
        [0.9392, 0.8653, 0.5782, 0.4651]])
tensor([[ 2.6795,  0.3322,  1.3281, -1.1808],
        [ 0.7795,  1.1799,  2.1769,  0.3805]])


### 덧셈2

In [14]:
print(torch.add(x, y))

tensor([[ 2.6795,  0.3322,  1.3281, -1.1808],
        [ 0.7795,  1.1799,  2.1769,  0.3805]])


### 덧셈3
- 결과 텐서를 인자로 제공

In [15]:
result = torch.empty(2, 4)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.6795,  0.3322,  1.3281, -1.1808],
        [ 0.7795,  1.1799,  2.1769,  0.3805]])


### 덧셈4
- `in-place` 방식

- (참고) in-place 방식
  - in-place방식으로 텐서의 값을 변경하는 연산 뒤에는 _''가 붙음
  - `x.copy_(y), x.t_()`

In [16]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[ 2.6701,  0.0134,  0.5553, -2.0652],
        [-0.1597,  0.3146,  1.5987, -0.0846]])
tensor([[0.0093, 0.3187, 0.7728, 0.8845],
        [0.9392, 0.8653, 0.5782, 0.4651]])
tensor([[ 2.6795,  0.3322,  1.3281, -1.1808],
        [ 0.7795,  1.1799,  2.1769,  0.3805]])


### 그 외의 연산
- `torch.sub` : 뺄셈

- `torch.mul` : 곱셉

- `torch.div` : 나눗셈

- `torch.mm` : 내적(dot product)

In [19]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4], 
                  [6,8]])

print(x - y)

print(torch.sub(x, y))
print(x.sub(y))

tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [20]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4], 
                  [6,8]])

print(x / y)

print(torch.div(x, y))
print(x.div(y))

tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])
tensor([[0.5000, 0.7500],
        [0.8333, 0.8750]])


In [22]:
x = torch.Tensor([[1,3],
                  [5,7]])
y = torch.Tensor([[2,4], 
                  [6,8]])

print(torch.mm(x, y))
# 행렬곱

tensor([[20., 28.],
        [52., 76.]])


## 텐서의 조작(manipulations)

### 인덱싱
- 넘파이처럼 인덱싱 사용가능

In [23]:
print(x)

tensor([[1., 3.],
        [5., 7.]])


In [24]:
print(x[:,1])

tensor([3., 7.])


### view
- 텐서의 크기(size)나 모양(shape)을 변경

In [26]:
x = torch.rand(4,5)
y = x.view(20)

z = x.view(5, -1)

print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 5])
torch.Size([20])
torch.Size([5, 4])


### item
- 텐서에 값이 단 하나라도 존재하면 숫자값을 얻을 수 있음


In [27]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.5264])
-0.5263929963111877
torch.float32


- 스칼라값 하나만 존재해야함

In [29]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.6614])
0.6614357829093933
torch.float32


### squeeze 
- 차원을 축소(제거)

In [32]:
tensor = torch.rand(1, 3, 3)

print(tensor)
print(tensor.shape)

tensor([[[0.3237, 0.8285, 0.2019],
         [0.0772, 0.4780, 0.4534],
         [0.8358, 0.6918, 0.5335]]])
torch.Size([1, 3, 3])


In [31]:
t = tensor.squeeze()

print(t)
print(t.shape)

tensor([[0.3837, 0.0077, 0.8537],
        [0.5736, 0.5588, 0.2554],
        [0.9028, 0.9402, 0.4334]])
torch.Size([3, 3])


### unsqueeze
- 차원을 증가(생성)

In [33]:
t = tensor.unsqueeze(dim=0)

print(t)
print(t.shape)

tensor([[[[0.3237, 0.8285, 0.2019],
          [0.0772, 0.4780, 0.4534],
          [0.8358, 0.6918, 0.5335]]]])
torch.Size([1, 1, 3, 3])


### stack
- 텐서간 결합

In [35]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x,y,z]))


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### cat
- 텐서를 결합하는 메소드(concatenate)

- 넘파이의 `stack`과 유사하지만, 쌓을 dim이 존재해야함
  - 예를 들어, 해당 차원을 늘려준 후 결합


In [39]:
a = torch.rand(1,3,3)
b = torch.rand(1,3,3)
c = torch.cat((a,b), dim=2)
print(c)
print(c.size())

tensor([[[0.1780, 0.0029, 0.7164, 0.3518, 0.2038, 0.5834],
         [0.2505, 0.7494, 0.6302, 0.7549, 0.1523, 0.4847],
         [0.2568, 0.0559, 0.5764, 0.4404, 0.4168, 0.6016]]])
torch.Size([1, 3, 6])


### chuck
- 텐서를 여러 개로 나눌 때 사용

- 몇 개의 텐서로 나눌 것이냐

In [40]:
tensor= torch.rand(3,6)
t1, t2, t3 = torch.chunk(tensor, 3, dim=1)

print(tensor)
print(t1)
print(t2)
print(t3)

tensor([[0.9211, 0.4610, 0.1840, 0.3177, 0.4037, 0.7762],
        [0.8645, 0.0345, 0.3111, 0.5707, 0.2412, 0.2379],
        [0.3063, 0.1656, 0.8572, 0.1694, 0.6979, 0.8297]])
tensor([[0.9211, 0.4610],
        [0.8645, 0.0345],
        [0.3063, 0.1656]])
tensor([[0.1840, 0.3177],
        [0.3111, 0.5707],
        [0.8572, 0.1694]])
tensor([[0.4037, 0.7762],
        [0.2412, 0.2379],
        [0.6979, 0.8297]])


### split
- `chunck`와 동일한 기능이지만 조금 다름

- 하나의 텐서당 크기가 얼마이냐

In [42]:
tensor = torch.rand(3,6)
t1, t2 = torch.split(tensor, 3, dim=1) #텐서당 크기라는 의미 3 <<

print(tensor)
print(t1)
print(t2)

tensor([[0.7816, 0.7839, 0.7046, 0.7256, 0.7919, 0.1446],
        [0.6030, 0.5470, 0.8803, 0.4211, 0.2508, 0.5325],
        [0.7953, 0.2617, 0.4709, 0.4094, 0.8579, 0.8993]])
tensor([[0.7816, 0.7839, 0.7046],
        [0.6030, 0.5470, 0.8803],
        [0.7953, 0.2617, 0.4709]])
tensor([[0.7256, 0.7919, 0.1446],
        [0.4211, 0.2508, 0.5325],
        [0.4094, 0.8579, 0.8993]])


### torch ↔ numpy
- Torch Tensor(텐서)를 Numpy array(배열)로 변환 가능

  - `numpy()`
  - `from_numpy()`

- (참고)
  - Tensor가 CPU상에 있다면 Numpy 배열은 메모리 공간을 공유하므로 하나가 변하면, 다른 하나도 변함

In [43]:
a = torch.ones(7)
print(a)

tensor([1., 1., 1., 1., 1., 1., 1.])


In [45]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1. 1. 1.]


In [49]:
a.add_(1)
print(a)
print(b)

tensor([5., 5., 5., 5., 5., 5., 5.])
[5. 5. 5. 5. 5. 5. 5.]


In [56]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)

np.add(a, 1, out=a)

print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
- `.to` 메소드를 사용하여 텐서를 어떠한 장치로도 옮길 수 있음
  - 예) cpu, gpu

In [57]:
import torch

In [58]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.4787])
-0.47868451476097107
torch.float32


In [60]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
print(device)
print(z)
print(z.to("cpu", torch.double))


cuda
tensor([0.5213], device='cuda:0')
tensor([0.5213], dtype=torch.float64)


## AUTOGRAD (자동미분)
- autograd 패키지는 Tensor의 모든 연산에 대해 **자동 미분** 제공

- 이는 코드를 어떻게 작성하여 실행하느냐에 따라 역전파가 정의된다는 뜻

- backprop를 위한 미분값을 자동으로 계산

### Tensor

- data: tensor형태의 데이터

- grad: data가 겨쳐온 layer에 대한 미분값 저장

- grad_fn: 미분값을 계산한 함수에 대한 정보 저장 (어떤 함수에 대해서 backprop 했는지)

- `requires_grad` 속성을 `True`로 설정하면, 해당 텐서에서 이루어지는 모든 연산들을 추적하기 시작

- 계산이 완료된 후, `.backward()`를 호출하면 자동으로 `gradient`를 계산할 수 있으며, `.grad` 속성에 누적됨

- 기록을 추적하는 것을 중단하게 하려면, `.detach()`를 호출하여 연산기록으로부터 분리

- 기록을 추적하는 것을 방지하기 위해 코드 블럭을 `with torch.no_grad():`로 감싸면 `gradient`는 필요없지만, `requires_grad=True`로 설정되어 학습 가능한 매개변수를 갖는 모델을 평가(evaluate)할 때 유용

- Autograd 구현에서 매우 중요한 클래스 : `Function` 클래스

In [61]:
import torch

In [63]:
x = torch.ones(3, 3, requires_grad= True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [65]:
y = x + 5
print(y)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [66]:
print(y.grad_fn)

In [67]:
z = y * y * 2

out = z.mean()

print(z, out)

tensor([[72., 72., 72.],
        [72., 72., 72.],
        [72., 72., 72.]], grad_fn=<MulBackward0>) tensor(72., grad_fn=<MeanBackward0>)


- `requires_grad_(...)`는 기존 텐서의 `requires_grad`값을 바꿔치기(`in-place`)하여 변경

In [68]:
a = torch.randn(3,3)
a = ((a*3)/ (a-1))

print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

b = (a * a).sum()
print(b.grad_fn)

False
True


### 기울기(Gradient)
- 역전파: `.backward()`를 통해 역전파 계산 가능

In [69]:
out.backward()

In [70]:
print(x.grad)

tensor([[2.6667, 2.6667, 2.6667],
        [2.6667, 2.6667, 2.6667],
        [2.6667, 2.6667, 2.6667]])


In [71]:
x = torch.randn(3, requires_grad = True)
y = x * 2

while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([586.5972, 606.4866, 748.4128], grad_fn=<MulBackward0>)


In [72]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


- `with torch.no_grad()`를 사용하여 gradient의 업데이트를 하지 않음

In [74]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

True
True
False


- `detach()`: 내용물(content)은 같지만 require_grad가 다른 새로운 Tensor를 가져올 때

### 자동 미분 흐름 다시 보기(1)
- 계산 흐름  
  $a \rightarrow b  \rightarrow c  \rightarrow out $

<br>

## $\quad \frac{\partial out}{\partial a} = ?$
- `backward()`를 통해  
  $a \leftarrow b  \leftarrow c  \leftarrow out $을 계산하면  
    $\frac{\partial out}{\partial a}$값이 `a.grad`에 채워짐


- $b = a + 2$

- $c = b^2$ 

- a의 `grad_fn`이 None인 이유  
  직접적으로 계산한 부분이 없었기 때문

### 자동 미분 흐름 다시 보기(2)
- `grad`값을 넣어서 `backward`

- 아래의 코드에서 `.grad`값이 None은 gradient값이 필요하지 않기 때문

## nn & nn.functional

- 두 패키지가 같은 기능이지만 방식이 조금 다름

- 위의 `autograd` 관련 작업들을 두 패키지를 통해 진행할 수 있음

- 텐서를 직접 다룰 때 `requires_grad`와 같은 방식으로 진행할 수 있음

- 결론적으로, `torch.nn`은 attribute를 활용해 state를 저장하고 활용하고,  
  `torch.nn.functional`로 구현한 함수의 경우에는 인스턴스화 시킬 필요 없이 사용이 가능
 


### nn 패키지

- 주로 가중치(weights), 편향(bias)값들이 내부에서 자동으로 생성되는 레이어들을 사용할 때  
  - 따라서, `weight`값들을 직접 선언 안함

- 예시
  - Containers

  - Convolution Layers

  - Pooling layers

  - Padding Layers

  - Non-linear Activations (weighted sum, nonlinearity)

  - Non-linear Activations (other)

  - Normalization Layers

  - Recurrent Layers

  - Transformer Layers

  - Linear Layers

  - Dropout Layers

  - Sparse Layers

  - Distance Functions

  - Loss Functions

  - ..
- https://pytorch.org/docs/stable/nn.html



- Convolution Layer 예시 (1)


### nn.functional 패키지

- 가중치를 직접 선언하여 인자로 넣어줘야함

- 예시)
  - Convolution functions

  - Pooling functions
  
  - Non-linear activation functions

  - Normalization functions

  - Linear functions

  - Dropout functions
  
  - Sparse functions
  
  - Distance functions

  - Loss functions
  - ..

- https://pytorch.org/docs/stable/nn.functional.html

- Convolution Layer 예시 (2)

## Torchvision

- `transforms`: 전처리할 때 사용하는 메소드

- `transforms`에서 제공하는 클래스 이외에  
  일반적으로 클래스를 따로 만들어 전처리 단계를 진행
  
  - 아래의 코드에서 다양한 전처리 기술 확인  
    https://pytorch.org/docs/stable/torchvision/transforms.html


- 예시)
  - `DataLoader`의 인자로 들어갈 `transform`을 미리 정의할 수 있음

  - `Compose`를 통해 리스트 안에 순서대로 전처리 진행

  - 대표적인 예로, `ToTensor`()를 하는 이유는  
   <u>torchvision이 PIL Image형태로만 입력을 받기 때문에</u> 데이터 처리를 위해서 Tensor형으로 변환해야함

## utils.data

- `Dataset`에는 다양한 데이터셋이 존재  
  - MNIST, CIFAR10, ...

- `DataLoader`, `Dataset`을 통해  
  `batch_size`, `train`여부, `transform`등을 인자로 넣어 데이터를 어떻게 load할 것인지 정해줄 수 있음

- `batch_size`만큼 데이터를 하나씩 가져옴

<u>**(중요) torch에서는 channel(채널)이 앞에 옴**</u>

- `channel first`

- tensorflow, keras 등에서는 channel이 뒤에 옴(`channel last`)

### 데이터 확인

## 각 Layer 설명

### nn.Conv2d

- `in_channels`: channel의 갯수

- `out_channels`: 출력 채널의 갯수

- `kernel_size`: 커널(필터) 사이즈

- 텐서플로우, 케라스와 다르게 레이어의 `input`인자에도 값을 집어 넣어줘야함

- `wegiht`확인

- `weight`는 `detach()`를 통해 꺼내줘야 `numpy()`변환이 가능

### Pooling
- `F.max_pool2d` 
  - `stride`

  - `kernel_size`

- `torch.nn.MaxPool2d` 도 많이 사용

- MaxPool Layer는 weight가 없기 때문에 바로 `numpy()`변환 가능

### Linear
- 1d만 가능 `.view()`를 통해 1D로 펼쳐줘야함

### Softmax

### F.relu

- ReLU 함수를 적용하는 레이어

- `nn.ReLU`로도 사용 가능

## Optimizer

- `import torch.optim as optim`

- `model`의 파라미터를 업데이트

- 예시)
  ```python
  optimizer = torch.optim.Adam(model.parameters(), lr=1e-4, weight_decay=1e-5)
  optimizer = optim.SGD(model.parameters(), lr=0.001)
  ```

- `.zero_grad()`로 초기화
- `.step()`으로 업데이트

